### PR TITLE
New tutorial chapter: dependent select dropdowns

### PR DESCRIPTION
**Pull request by MehulKChaudhari**
## Summary 
Add the `Dependent Select dropdowns` tutorial.

Issue: #859 - [comment](https://github.com/NullVoxPopuli/limber/issues/859#issuecomment-1625516590)

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
Thanks for working on this!!! 

idk if it helps, but here is one I did recently: https://github.com/NullVoxPopuli/limber/pull/1151/files#diff-3e25f191965223d42cb624fe00b4c07962b76a6e591b7131f1645961097e790e

**Comment by MehulKChaudhari** [comment]
> Thanks for working on this!!!
> 
> idk if it helps, but here is one I did recently: https://github.com/NullVoxPopuli/limber/pull/1151/files#diff-3e25f191965223d42cb624fe00b4c07962b76a6e591b7131f1645961097e790e

Yes this is helpful. I will make the changes.

**Comment by NullVoxPopuli** [comment]
hello @MehulKChaudhari !! is this something you're still wanting to finish? 

this looks like good content!

**Comment by MehulKChaudhari** [comment]
> hello @MehulKChaudhari !! is this something you're still wanting to finish?
> 
> this looks like good content!

I wanted to make some changes after taking your suggestions into account. I have made a few changes but will need to curate and polish them for the final review and merge

**Comment by NullVoxPopuli** [comment]
I need to fix PR commenting from forks, but

| Project   | Preview URL[^note] | Manage | 
| -------   | ------------------ | ------ |
| Limber    | https://tutorial-/depedent-select-dropdowns.limber-glimdown.pages.dev   | [on Cloudflare](https://dash.cloudflare.com/c67910a047e1510fec6d0d0cf442934c/pages/view/limber-glimdown) | 
| Tutorial  | https://tutorial-/depedent-select-dropdowns.limber-glimmer-tutorial.pages.dev | [on Cloudflare](https://dash.cloudflare.com/c67910a047e1510fec6d0d0cf442934c/pages/view/limber-glimmer-tutorial)

[Logs](https://github.com/NullVoxPopuli/limber/actions/runs/11189682697) 

[^note]: if these branch preview links are not working, please check the logs for the commit-based preview link. There is a character limit of 28 for the branch subdomain, as well as some other heuristics, [described here](https://community.cloudflare.com/t/algorithm-to-generate-a-preview-dns-subdomain-from-a-branch-name/477633?u=walshymvp) for the sake of implementation ease in deploy-preview.yml, that algo has been omitted.  The URLs are logged in the wrangler output, but it's hard to get outputs from a matrix job.

**Pull request merged**
